" Pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" General
let mapleader = ","
set nowrap
set cursorline
set modeline

" Highlighting Search
set hlsearch
map <Leader>hs :noh<CR>

"Autoformat
map <Leader>f :Autoformat<CR>

" Tabs
set tabstop=2 shiftwidth=2 expandtab

" NerdTree
map <Leader>n :NERDTreeToggle<CR>

" Visuals
colorscheme xoria256

" Show Line numbers
set number

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" viminfo
" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo'

" PHP tabs
autocmd FileType php set tabstop=4 shiftwidth=4 expandtab
