# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew bower composer history-substring-search git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export EDITOR='vim'
export HOMEBREW_GITHUB_API_TOKEN=f442262850ccba56c509ce0d0931e4082991d1b2

## Conditional PATH
###################
if which npm > /dev/null; then
  export PATH="$PATH:$(npm bin)"
  export PATH=$HOME/.node/bin:$PATH
else
  echo "npm not found";
fi

# Include some extra functions
. "${HOME}/.sugar"

# Just computer specific stuff
. "${HOME}/.privaterc" &>/dev/null

# Add Establish to PATH
export PATH="$PATH:$HOME/.establish/bin"

# local vendor bin to PATH
export PATH="$PATH:./vendor/bin"

# Add sassy to PATH
export PATH="$PATH:$HOME/.sassy/bin"

# rbenv
eval "$(rbenv init -)"
